### ISSUE TITLE
Issue using the graphqlite bundle with multiple namespaces for types and controllers

### ISSUE THREAD

**Issue by aszenz** [thecodingmachine/graphqlite-bundle#103]
I recently added a new namespace for types and controllers to the bundle config but got some weird errors related to not finding any fields for graphql types. 

Looks like the bundle was searching for types in the wrong directory. When i moved the code into the same namespace it all worked again, so I'm just wondering if there's a bug with the types finding logic when configured with multiple namespaces

I received these kinds of errors:

```
The GraphQL object type \"Propagation\" has no fields defined. Please check that some fields are defined (using the @Field annotation). If some fields are defined, please check that at least one is visible to the current user.",
```

The propagation object type was defined with fields, but it seems to be looking at the actual class not the external type class.

We use php config graphqlite.php for symfony:

```php
<?php

declare(strict_types=1);

namespace Symfony\Component\DependencyInjection\Loader\Configurator;

use Symfony\Config\GraphqliteConfig;

return static function (ContainerConfigurator $containerConfigurator, GraphqliteConfig $config): void {
    $config
        ->namespace()
        ->controllers([
            'Corp\Order\UI\GraphQL\Resolvers\\',
            'Corp\Foo\Bar\Z\Resolvers\\',
        ])
        ->types([
            'Corp\Order\UI\GraphQL\Types\\',
            'Corp\Foo\Bar\Z\Types\\',
        ])
    ;
};
```

**Comment by aszenz** [comment]
Note we discussed this issue first here https://github.com/thecodingmachine/graphqlite/discussions/385

**Comment by nguyenk** [comment]
@moufmouf any clue ?

**Comment by aszenz** [comment]
This was an old issue, we now use multiple namespaces already and it works fine, so closing this
