### ISSUE TITLE
Updating latest release tag to 5.0

### ISSUE THREAD

**Issue by MattBred** [thecodingmachine/graphqlite-bundle#106]
Now that GraphQLite is 4.3.x, should we update composer.json + this package tag to better match?

This comment specifically mentions it: https://github.com/thecodingmachine/graphqlite-bundle/pull/86#issuecomment-851246459

**Comment by MattBred** [comment]
+ @devmaslov

**Comment by devmaslov** [comment]
The bundle has been updated to the 5th version of GraphQLite! Check out the release note:
https://github.com/thecodingmachine/graphqlite-bundle/releases/tag/v5.0.0
