### ISSUE TITLE
Symfony 6

### ISSUE THREAD

**Issue by classic-o** [thecodingmachine/graphqlite-bundle#115]
Hi. Do you have the plan and timeline for migration to symfony 6

**Comment by mistraloz** [comment]
Do you have any issue in symfony 6 ? I've migrate successfully to sf 5.4 so it's may about the same for 6.0

**Comment by classic-o** [comment]
"symfony/framework-bundle": "^4.2 || ^5"

**Comment by classic-o** [comment]
Need to allow ^6
"symfony/framework-bundle": "^4.2 || ^5",
