### ISSUE TITLE
Release a bundle version for GraphQLite 6

### ISSUE THREAD

**Issue by homersimpsons** [thecodingmachine/graphqlite-bundle#142]
GraphQLite 6 is out :tada: https://github.com/thecodingmachine/graphqlite/releases/tag/v6.0.0

This bundles should be upgraded to the latest version

**Comment by martincodes-de** [comment]
@mistraloz is it possibile for you to do that?

**Comment by mistraloz** [comment]
Hello @martincodes-de, sorry i can not for instance. :no_good:

**Comment by martincodes-de** [comment]
Do you know who can do it?

**Comment by martincodes-de** [comment]
> Hello @martincodes-de, sorry i can not for instance. :no_good: 

Do you know who can do it?

**Comment by mistraloz** [comment]
Currently, on TCM side, we will not participate to this subject until 11th (at least). But community contribution are welcome and may be managed by community maintainers of graphqlite (i just saw this PR this morning https://github.com/thecodingmachine/graphqlite-symfony-validator-bridge/pull/65 and if i'm well remember it's a good starting point to update of this bundle). If needed, and if there are community review on theses PR, i can merge them. 

Please note, we will not abandon this graphqlite suite, it's important for us too. But currently we have others priorities.

**Comment by aszenz** [comment]
Anything preventing the release of v6, the symfony 6 is still unmerged

**Comment by aszenz** [comment]
I mean that the pr https://github.com/thecodingmachine/graphqlite-symfony-validator-bridge/pull/65 is still unmerged

**Comment by WizMik** [comment]
Any news on that ? We're looking forward to upgrade our ecosystem to latest Symfony + GraphQLite (interested about https://github.com/thecodingmachine/graphqlite-bundle/issues/137 also)

**Comment by jroszkiewicz** [comment]
bump bump guys, I don't want to freeze my projects to old code :(
any chance to resolve this blocker?

**Comment by JacynoAdam** [comment]
@mistraloz Do you by any chance have a list of things that will need to be done to get this working, apart from the validator bridge update? Haven't done any work on this package yet, but I would like to help get this updated if I can.

**Comment by jroszkiewicz** [comment]
@mistraloz 
https://github.com/thecodingmachine/graphqlite-symfony-validator-bridge/pull/65#issuecomment-1381493548

As you see new release with symfony 6 is published :)
Can we move this task now?

**Comment by WizMik** [comment]
Hi guys, tomorrow it's Valentines Day, please show us some love 🥰

**Comment by jroszkiewicz** [comment]
Bump guys, cmon.
For what we waiting now? ;p

**Comment by marcinjagielnicki** [comment]
Any news on this?

**Comment by johnzuk** [comment]
Is this bundle still under development by anyone? This issue is almost one year old :(

**Comment by nguyenk** [comment]
Hey folks I just drafted realease [v6.0.0-beta.0](https://github.com/thecodingmachine/graphqlite-bundle/tree/v6.0.0-beta.0)

As I'm not using the bundle in any project right now, I'd need you to test. I just made is possible to instal, and fixed the CI, so please report, or event better submit a PR for fixes.

cc: @jroszkiewicz @marcinjagielnicki @johnzuk
