### ISSUE TITLE
ServerConfig doesn't match GraphQL\Server\ServerConfig with Symfony 6, GQLite 6

### ISSUE THREAD

**Issue by christian-lorenz** [thecodingmachine/graphqlite-bundle#173]
public function setValidationRules($validationRules)

needs the return value -> :self

Also there's some f* up with Graphqlite and GraphQLite (like at bundles.php), but this I could fix locally

**Comment by nguyenk** [comment]
@christian-lorenz  we just released the SF 6 support in master, please check I think the issue is solved
