### ISSUE TITLE
New stable version

### ISSUE THREAD

**Issue by wollukav** [thecodingmachine/graphqlite-bundle#179]
Hi everyone,

https://github.com/thecodingmachine/graphqlite-bundle/issues/142 based on this discussion it was realease beta version.
I see that we have already had diff between beta and the main branch. At least `thecodingmachine/graphqlite-symfony-validator-bridge` point to stable version.

Do you have plans to release a stable version?

**Comment by nguyenk** [comment]
Hello @wollukav ,

Simple and stupid, I just forgot to create the stabe tag. I tagged `thecodingmachine/graphqlite-symfony-validator-bridge` and needed to tage this repo. 

But then I just forgot...

Anyway it's done now.
