### ISSUE TITLE
Support overblog/graphiql-bundle: ^1.0

### ISSUE THREAD

**Issue by aszenz** [thecodingmachine/graphqlite-bundle#193]
Currently the package limit to 0.2/0.3

https://github.com/overblog/GraphQLBundle

**Comment by andrew-demb** [comment]
> > The correct link should be a https://github.com/overblog/GraphiQLBundle
> 
> Yes the broader goal is to have Symfony 7 support

There's no versions after 0.3.0 for this bundle

**Comment by aszenz** [comment]
> > > The correct link should be a https://github.com/overblog/GraphiQLBundle
> > 
> > Yes the broader goal is to have Symfony 7 support
> 
> There's no versions after 0.3.0 for this bundle

Hmm this link https://github.com/overblog/GraphQLBundle does have a version 1 and is more upto date, maybe they changed the name

**Comment by aszenz** [comment]
Oh I see what is going on, the other bundle is a graphql library, while we only include the graphiql playground

**Comment by aszenz** [comment]
I see an issue already for Symfony 7
https://github.com/overblog/GraphiQLBundle/issues/39

**Comment by aszenz** [comment]
Closing this issue will create another issue for symfony 7
