### ISSUE TITLE
Enable wiki

### ISSUE THREAD

**Issue by fogrye** [thecodingmachine/graphqlite-bundle#204]
The [graphqlite](https://github.com/thecodingmachine/graphqlite/issues/376) waits for moving docs to corresponding projects, I can help with that. I think wiki is great place to have them, could maintainer enable it?

**Comment by homersimpsons** [comment]
Looks like the wiki already existed: https://github.com/thecodingmachine/graphqlite-bundle/wiki

I just made it editable by anyone. Feel free to edit it. I may lock it again in the future to avoid vandalism (but not lanned for now).
