### ISSUE TITLE
package abandoned?

### ISSUE THREAD

**Issue by jroszkiewicz** [thecodingmachine/graphqlite-bundle#219]
This project appears to have been abandoned. Unfortunately, we are still waiting for a new release with symfony 7.* support.
Maybe it's time to talk about an alternative, or maybe fork this project?

**Comment by homersimpsons** [comment]
> This project appears to have been abandoned.

More or less. I'm still keeping an eye on it but I'm not contributing to it.

> Unfortunately, we are still waiting for a new release with symfony 7.* support.

This should be rather close to release with #203. I would be happy to publish a new release when this pull request get merged. But the performance issue in this pull request seems concerning. I may still merge it as-is and release a beta version so more people could use it.

> or maybe fork this project?

I'm not sure this would be the best. I think the best option currently is to push #203 forward. I may take time to push it on the next week but for now I do not intend to.

**Comment by enricobono** [comment]
Hello @homersimpsons.
[My company](https://www.linkedin.com/company/switcho/) and I can help in maintaining this bundle and the entire [graphqlite](https://github.com/thecodingmachine/graphqlite) lib, if needed. Is there anything we can help you guys with?
